# Generated by Django 4.2.3 on 2023-08-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0005_onlineshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshop',
            name='image',
            field=models.ImageField(blank=True, upload_to='online_shop/', verbose_name='Изображение'),
        ),
    ]
